### ISSUE TITLE
Windows tests fail

### ISSUE THREAD

**Issue by HolyPrapor** [vostok/hercules.client#14]
I [once tried to fix](https://github.com/vostok/hercules.local/commit/1533c85a8859aff7f1a85d3d0de30f958c02a1b0) this, but didn't find a quick solution..

**Comment by kungasc** [comment]
Topic deletion should be disabled for Windows

**Comment by HolyPrapor** [comment]
Disabled topic deletion on Windows due to Kafka's guarantees
