### ISSUE TITLE
Implement sending of self-diagnostic metrics to Hercules

### ISSUE THREAD

**Issue by epeshk** [vostok/hercules.client#4]
Self-diagnostics data should use independent buffer pool (memory manager).

**Comment by kungasc** [comment]
Started here: https://github.com/vostok/hercules.client.metrics.
But too ugly to use and set up.

**Comment by kungasc** [comment]
Implemented at Vostok.Host.
https://github.com/vostok/hosting/blob/aaa74f3717718ac6563501c3223646dc3b5a4698/Vostok.Hosting/Components/Hercules/HerculesSinkMetrics.cs
